# Generated by Django 5.2 on 2025-06-05 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('can_edit_course_image', 'Может редактировать изображение курса')]},
        ),
    ]
