# Generated by Django 5.2 on 2025-06-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/previews/'),
        ),
    ]
